### ISSUE TITLE
StyledText does not rebuild when setState updates variables. 

### ISSUE THREAD

**Issue by InroEn** [andyduke/styled_text_package#10]
I used the widget with the style : StyledText(fontFamily, fontSize and height) properties which gets updated when the user changes these settings but the widget does not adjust to these changes. The hierarchy tree is: Consumer->FutureBuilder->ListView.builder()->ListTile() and within the title property I use the StyledText()

**Comment by andyduke** [comment]
@TheObviousChico 
Fixed and posted on pub.dev.

**Comment by InroEn** [comment]
> @TheObviousChico
> Fixed and posted on pub.dev.

Thanks and greatly appreciated.

**Comment by InroEn** [comment]
> @TheObviousChico
> Fixed and posted on pub.dev.

The bug has been fix but now when it rebuilds, it now double flashes each time when the screen rebuilds. I tried it with a normal RichText() widget to make sure and it worked normal.

**Comment by andyduke** [comment]
@TheObviousChico 
Fixed and published on pub.dev.
