### ISSUE TITLE
double quotes won't show

### ISSUE THREAD

**Issue by edwinaceron** [andyduke/styled_text_package#11]
How would I show the double quotes? I did use replaceAll that would replace double quote with \" but still it won't show.

**Comment by andyduke** [comment]
> How would I show the double quotes? I did use replaceAll that would replace double quote with " but still it won't show.

Try `&quot;` instead of "

**Comment by edwinaceron** [comment]
> > How would I show the double quotes? I did use replaceAll that would replace double quote with " but still it won't show.
> 
> Try `&quot;` instead of "

thanks andy!
