### ISSUE TITLE
Removes single and double quotations from the String being displayed.

### ISSUE THREAD

**Issue by InroEn** [andyduke/styled_text_package#13]
Say, I want to display.
i.e: Lisa asked Shane "How was the weather?" asked Lisa.
I want to display the quotations marks but it's being trim out and doesn't even leaves the spacing between the words. Like I'''''''''m -> I    m but does Im instead.
Also using a raw string does not seem to help.
Ran through the code and saw that I could use [& a p o s ;] in my String to get the ' character but it would be nice to use ' " in the String itself.

Thanks in advance.

**Comment by andyduke** [comment]
Replace the quotation mark `"` with `&quot;`

Example:
```dart
StyledText(
  text: 'Quoted Test: <b>&quot;bold&quot;</b> text.',
  styles: {
    'b': TextStyle(fontWeight: FontWeight.bold),
  },
),
```
Will be drawn as:
Quoted Test: **"bold"** text.

**Comment by InroEn** [comment]
Yes, in which I found out by going through the source code but most people wouldn't know that so it at least needs to be documented. 🙂

**Comment by andyduke** [comment]
> 
> 
> Yes, in which I found out by going through the source code but most people wouldn't know that so it at least needs to be documented. 🙂

I've added an escaping instruction to the documentation.
