### ISSUE TITLE
No named parameter with the name 'cursorHeight'

### ISSUE THREAD

**Issue by shreyas18jan** [andyduke/styled_text_package#14]
I imported the dependency, tried to run my sample code. I'm seeing No named parameter with the name 'cursorHeight' issue.

![Screen Shot 2020-11-23 at 8 05 38 AM](https://user-images.githubusercontent.com/16950889/99928501-5f64e680-2d6f-11eb-87f2-04aee0c7feef.png)
![Screen Shot 2020-11-23 at 8 08 26 AM](https://user-images.githubusercontent.com/16950889/99928506-625fd700-2d6f-11eb-97aa-3559481512d3.png)

I took this dependency - `https://pub.dev/packages/styled_text/install`
I have added my flutter version used and I have also added the screenshot where Run main.dart has given the exception.

To check the usage of styled_text, Locally I removed the reference of cursorHeight entries in `styled_text/styled_text.dart`. It started working fine. Please have a look.
![Screen Shot 2020-11-23 at 9 46 35 AM](https://user-images.githubusercontent.com/16950889/99928824-d2229180-2d70-11eb-8af6-29713d854f4f.png)

**Comment by andyduke** [comment]
@shreyas18jan You need to update Flutter to the latest stable version.

**Comment by shreyas18jan** [comment]
Thanks, After taking latest stable version it started working fine.

Closing this issue.
![Screen Shot 2020-11-24 at 11 28 26 AM](https://user-images.githubusercontent.com/16950889/100054511-2d738300-2e48-11eb-94db-648e934179a8.png)
