### ISSUE TITLE
Apostrophe character not shown in my text

### ISSUE THREAD

**Issue by Fabio-Paccosi** [andyduke/styled_text_package#15]
When I try to show styled text I cannot see apostrophe character:

`StyledText(
                  text: "Bell'articolo",
                  TextAlign: TextAlign.left, 
                  style: ArticleTextStyle.getAbstractStyle(text_color: "#000000", font_size: 16),
                  styles: {
                    //Text styles
                    'u': ArticleTextStyle.getAbstractStyle(text_color: "#000000", font_size: 16, is_underline: true),
                    'b': ArticleTextStyle.getAbstractStyle(text_color: "#000000", font_size: 16, is_bold: true),
                    'i': ArticleTextStyle.getAbstractStyle(text_color: "#000000", font_size: 16, is_italic: true),
                  },
                )*

Return this: "bellarticolo"

When I use standard Flutter Text() class I see "Bell'articolo" correctly.

Have you ever encountered this problem?

Thanks

**Comment by andyduke** [comment]
@Fabio-Paccosi 
Some characters need to be escaped, see here - https://pub.dev/documentation/styled_text/latest/styled_text/StyledText/text.html

**Comment by Fabio-Paccosi** [comment]
Thank you! I can close this issue
