### ISSUE TITLE
Color with hex values

### ISSUE THREAD

**Issue by jaumard** [andyduke/styled_text_package#16]
The API I'm using is returning this:

```
Attack primary target for <color=#86e619>80%</color> damage.\nGain <color=#fff568>Offense Up</color> + apply <color=#fff568>Offense Up</color> to adjacent <color=#fff568>A.I.M.</color> allies for <color=#86e619>2</color> turns.\n\nThis attack cannot miss.
```

Would be nice if this package can handle that kind of tag

**Comment by andyduke** [comment]
@jaumard 
Yes, that would be a nice feature. I'll add it in the near future.

**Comment by andyduke** [comment]
@jaumard 
I added a `CustomTextStyle` class to handle the attributes passed to tags. See example in README.md

**Comment by jaumard** [comment]
Nice! Thanks!

**Comment by Zabadam** [comment]
In the initial question, and through the usage of the referenced solution `CustomTextStyle()`, can "color" be both the `<tag>` and an `attr`?
