### ISSUE TITLE
Newline charater doesn't get converted to <br/>

### ISSUE THREAD

**Issue by CodeSpartan** [andyduke/styled_text_package#18]
This code works fine:
```
test = "<b>$name</b> hit <b>someone</b> with <i>a club</i>";
test += "<br/>";
test += "Next line message";
```
Result:
![img1](https://i.gyazo.com/9717f9a567e129202c3c054e2554d76b.png)

But this code produces a different result:
```
test = "<b>$name</b> hit <b>someone</b> with <i>a club</i>";
test += "\n";
test += "Next line message";
```
Result:
![img2](https://i.gyazo.com/03a54c649007f261f6877337525188f1.png)

The problem occurs on the latest version: 1.0.3+1

**Comment by CodeSpartan** [comment]
Ah, I see, it only works when newLineAsBreaks is set to true.
I think it should be true by default -- why wouldn't it? Anyway, closing the issue.

**Comment by andyduke** [comment]
@CodeSpartan For compatibility reasons with the first versions of StyledText and to better conform to the HTML standard.
