### ISSUE TITLE
Need to set hyper link for email and phone number

### ISSUE THREAD

**Issue by Brinfotech1407** [andyduke/styled_text_package#21]
For bold italic it is working fine i need to display the email with hyperlink and same as moblie number

**Comment by andyduke** [comment]
Perhaps this is what you want:
https://github.com/andyduke/styled_text_package/blob/c7acd7e9660671ffffc4000768acb5c9bbc72330/example/lib/main.dart#L146-L155

**Comment by Brinfotech1407** [comment]
I am working on chat app where user will enter email or phone no or url as a message so in that case i think i need to manually append this <link> tag ?

**Comment by andyduke** [comment]
@Brinfotech1407 Do you want to automatically convert a URL, email, or phone number in text into an tappable link?

**Comment by Brinfotech1407** [comment]
Yes exactly

**Comment by andyduke** [comment]
In this case, you need to use another package (for example [Cretezy/linkify](https://github.com/Cretezy/linkify)) to recognize URLs, e-mails and phone numbers and then convert them to text with xml tags, which can be used in StyledText.  Or use a package that does it all at once, for example [Cretezy/flutter_linkify](https://github.com/Cretezy/flutter_linkify).
