### ISSUE TITLE
 Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by hsiami** [andyduke/styled_text_package#22]
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: No element
 ListQueue.removeLast (dart:collection/queue.dart:767:25)
_StyledTextState._updateTextSpans.<anonymous closure> (package:styled_text/styled_text.dart:353:30)
_rootRunUnary (dart:async/zone.dart:1198:47)
_CustomZone.runUnary (dart:async/zone.dart:1100:19)
_CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
_DelayedData.perform (dart:async/stream_impl.dart:611:14)
_StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (11144): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
_rootRun (dart:async/zone.dart:1182:47)
_CustomZone.run (dart:async/zone.dart:1093:19)
_CustomZone.runGuarded (dart:async/zone.dart:997:7)
_CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
_rootRun (dart:async/zone.dart:1190:13)
_CustomZone.run (dart:async/zone.dart:1093:19)
_CustomZone.runGuarded (dart:async/zone.dart:997:7)
_CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
_microtaskLoop (dart:async/schedule_microtask.dart:41:21)
_startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by andyduke** [comment]
@hsiami Can you provide minimal code that reproduces this error and the output of `flutter doctor -v` command?

**Comment by hsiami** [comment]
It occurs when xml is malformed

**Comment by andyduke** [comment]
@hsiami Can you give an example of such xml?

**Comment by hsiami** [comment]
وَ اَللَّهِ لَقَدْ أَسَرَكَ اَلْكُفْرُ مَرَّةً وَ <em>اَلْإِسْلاَمُ</em> أُخْرَى فَمَا فَدَاكَ مِنْ وَاحِدَةٍ <phrase

**Comment by hsiami** [comment]
sorry, above example doesn't have problem. try this to produce the error:
"  hello world />"

**Comment by andyduke** [comment]
@hsiami I have improved handling of broken xml, sorry for the delay.
