### ISSUE TITLE
maxLines doesn't work for web

### ISSUE THREAD

**Issue by sumitasharma** [andyduke/styled_text_package#26]
Hi,

maxLines for web is not working if the text has multiple line text but the first line isn't long enough for the container that holds the text in it.
ex. If my text has 4 lines but the first line is short, maxLines doesn't work and shows the entire text.

I made changes to Container size to make the maxLine work.
 Container(width: (myText.toString().split('\n')[0].length > 70) ? 680 : 600)
Thanks

**Comment by andyduke** [comment]
@sumitasharma Is this problem still after upgrading to Flutter 2.0?

**Comment by sumitasharma** [comment]
Hi Andy,
Yes, it is worrking in Flutter 2.
Thanks
