### ISSUE TITLE
Error when building app when upgrade flutter

### ISSUE THREAD

**Issue by rezam92** [andyduke/styled_text_package#27]
When i try to compile project, i got this error because of upgrading flutter to version 2.1.0-12.2.pre

Error: The method 'CustomStyle.apply' has fewer named arguments than those of overridden method
class 'CustomTextStyle' is missing implementations for these members: - TextStyle.leadingDistribution

**Comment by andyduke** [comment]
@rezam92 I am waiting for the release of this version of Flutter.
