### ISSUE TITLE
How is an apostrophe to be placed in a StyledText?

### ISSUE THREAD

**Issue by jbenman** [andyduke/styled_text_package#3]
I might have a slightly strange use-case (storing lots of styled text strings as values in json files, so xml in a json file) but I can't seem to find a way to make apostrophes appear. This is true even when I run the example app and try to put a word with an apostrophe in one of the strings.

I've tried using the escape sequence: \\' but this has no effect on the output (and would be incorrect when stored in a json file regardless). I've tried using \&apos; and #39; but those are just output the way they appear. I also tried using double quotes around the strings and just using regular apostrophes, but those disappear too.

**Comment by jaymacdonald67** [comment]
I am also having an issue using an apostrophe.

**Comment by shredding** [comment]
Any chance we can merge this soon?

**Comment by shredding** [comment]
Thx!

**Comment by rdcoder33** [comment]
still apostrophe is not showing

**Comment by shredding** [comment]
Can you show your code? It needs to be written as `&quot;`
