### ISSUE TITLE
3.0.0-beta+2 still gives compile errors on beta channel

### ISSUE THREAD

**Issue by ryanheise** [andyduke/styled_text_package#32]
```
styled_text-3.0.0-beta+2/lib/custom_style.dart:7:7: Error: The non-abstract class 'CustomStyle' is missing implementations for these members:
 - TextStyle.leadingDistribution                                        
Try to either                                                           
 - provide an implementation,                                           
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                       
 - provide a 'noSuchMethod' implementation.

...
...
```

I think this class would need to be deprecated in a lower version, but it would need to be outright removed in the 3.0.0 release otherwise it will never compile on the latest Flutter.

**Comment by andyduke** [comment]
@ryanheise Wait for the new stable version of Flutter to be released, then I will make a version that will work with the new version of Flutter.

**Comment by ryanheise** [comment]
I couldn't wait since integration testing is critical in our case and Google's advice is to switch to beta for integration testing. However, if anyone else needs a fix for this issue, I've created a fork of the last stable version of styled_text that works on the beta channel:

https://github.com/ryanheise/styled_text_package/tree/flutter_beta

It's only a temporary solution until the new version of styled_text removes the incompatibility between flutter stable and beta channels.

**Comment by DennisLit** [comment]
@andyduke Flutter 2.2 out now, and package fails to compile on stable now.

**Comment by coodysk8er** [comment]
@andyduke  @ryanheise 's solution looks good. Can you help have the fix in? Thank you.

**Comment by andyduke** [comment]
@coodysk8er @ryanheise @DennisLit New version with Flutter 2.2 support already on [pub.dev](https://pub.dev/packages/styled_text)

**Comment by ryanheise** [comment]
> I couldn't wait since integration testing is critical in our case and Google's advice is to switch to beta for integration testing. However, if anyone else needs a fix for this issue, I've created a fork of the last stable version of styled_text that works on the beta channel:
> 
> https://github.com/ryanheise/styled_text_package/tree/flutter_beta
> 
> It's only a temporary solution until the new version of styled_text removes the incompatibility between flutter stable and beta channels.

Now that 3.0.0 is released, I'll schedule the above temporary repo for removal in about a month (to give time for anyone using it to move off it and onto the official 3.0.0.)
