### ISSUE TITLE
Could you support simple image

### ISSUE THREAD

**Issue by winterdl** [andyduke/styled_text_package#35]
Could you support render image tag, like icon tag, render thumbnail image with external link and fullscreen when tap on image. Thank you!

**Comment by andyduke** [comment]
@winterdl You can insert any widget into the text, see an [example here.](https://github.com/andyduke/styled_text_package/blob/master/styled_text/README.md#an-example-of-inserting-an-input-field-widget-in-place-of-a-tag)
