### ISSUE TITLE
Bold Text Accessibility

### ISSUE THREAD

**Issue by CassiusPacheco** [andyduke/styled_text_package#38]
Hi there,

first of all, thanks for the amazing work. This lib is great!

I managed to make use of the `textScaleFactor` when using `StyledText` but I noticed that the bold text accessibility option does not get applied to the text automatically.

Is there a way for me to achieve that at the current state of the lib or will it need extra customisation? If it needs extra customisation, would you be able to give me a bit of a direction to where I should be looking into in order to change this?

Thank you

**Comment by andyduke** [comment]
@CassiusPacheco Please provide the minimum code and screenshot to reproduce the problem so that I can better understand what the problem is.
