### ISSUE TITLE
new line support?

### ISSUE THREAD

**Issue by liudonghua123** [andyduke/styled_text_package#4]
I have text with new line break, but the text are all together.

**Comment by andyduke** [comment]
> I have text with new line break, but the text are all together.

What do you use to separate lines: `\n` or `<br/>` tag?

**Comment by liudonghua123** [comment]
I use multi line string like the following, I think it have the same meaning as `\n`.
```dart
var str1 = '''This is a
multi line string.
The third line.''';
```

**Comment by andyduke** [comment]
You need to insert the `<br/>` tag in the places where you want to have line breaks.
