### ISSUE TITLE
Custom Style: No named parameter with the name 'overflow'

### ISSUE THREAD

**Issue by guibsonarc** [andyduke/styled_text_package#45]
I find this error when running the project using this code snippet with flutter 2.2.1

Code snippet:
`StyledText(
  text: 'Example: <b>bold</b> text.',
  tags: {
    'b': StyledTextTag(style: TextStyle(fontWeight: FontWeight.bold)),
  },
)`

Error:
../../../.pub-cache/hosted/pub.dartlang.org/styled_text-3.0.4/lib/custom_style.dart:69:7: Error: No named parameter with the name 'overflow'.
      overflow: overflow,                                               
      ^^^^^^^^                                                          
../../../.pub-cache/hosted/pub.dartlang.org/styled_text-3.0.4/lib/custom_style.dart:138:7: Error: No named parameter with the name 'overflow'.
      overflow: overflow,                                               
      ^^^^^^^^                                                          
../../../.pub-cache/hosted/pub.dartlang.org/styled_text-3.0.4/lib/custom_style.dart:253:39: Error: The getter 'overflow' isn't defined for the class 'TextStyle'.
 - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('../../../fvm/versions/2.2.1/packages/flutter/lib/src/painting/text_style.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'overflow'.
  TextOverflow? get overflow => style.overflow;                         
                                      ^^^^^^^^                          
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/guibson/fvm/versions/2.2.1/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/Users/guibson/fvm/versions/2.2.1/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 14s

**Comment by andyduke** [comment]
@guibsonarc For Flutter 2.2.x you need to use StyledText 3.0.2.  If you want to use a more recent version of StyledText, then you need to update Flutter to version 2.5.x.

**Comment by guibsonarc** [comment]
@andyduke Thank you, worked fine!
