### ISSUE TITLE
3.0.4+1 "'CustomStyle.apply' has fewer named arguments" error with master.

### ISSUE THREAD

**Issue by patniemeyer** [andyduke/styled_text_package#47]
Getting a build error on the latest flutter master.  Thanks!

`../../../../../Development/Packages/flutter-sdk-master/.pub-cache/hosted/pub.dartlang.org/styled_text-3.0.4+1/lib/custom
_style.dart:17:13: Error: The method 'CustomStyle.apply' has fewer named arguments than those of overridden method
'TextStyle.apply'.
  TextStyle apply({
            ^
../../../../../Development/Packages/flutter-sdk-master/packages/flutter/lib/src/painting/text_style.dart:890:13:
Context: This is the overridden method ('apply').
  TextStyle apply({
            ^
`

**Comment by toeydevelopment** [comment]
I fixed it

for temporary fix you can install package as below:

styled_text:
    git:
      url: https://github.com/toeydevelopment/styled_text_package
      path: styled_text/

**Comment by andyduke** [comment]
Use version 4.0.0
