### ISSUE TITLE
New line character doesn't break text into new line

### ISSUE THREAD

**Issue by LugonjaAleksandar** [andyduke/styled_text_package#5]
When I want to format text like this: 
`"First line text and <link>click here</link>.\n\nSecond line of text.\n\nThird line."`

I expect that this text will be drawn in multiple lines, but what I see on my screen is that `\n` characters are completely ignored.  Any ideas on how to overcome this difficulty and use line breaks?

**Comment by andyduke** [comment]
You need to use `<br/>` to break line.
