### ISSUE TITLE
StyledText.selectable ignores newLines

### ISSUE THREAD

**Issue by ABausG** [andyduke/styled_text_package#62]
When using `StyledText.selectable` Line Breaks are not displayed.

| `StyledText` | `StyledText.selectable` |
| ------------ | ------------------------ |
| <img width="274" alt="image" src="https://user-images.githubusercontent.com/7288963/201322171-87fcc443-c03e-4729-92d3-d5d2a3a34071.png"> | <img width="268" alt="image" src="https://user-images.githubusercontent.com/7288963/201322271-8025b0cd-af7a-40da-ac7b-68d703facf31.png">
 |

**Comment by andyduke** [comment]
@ABausG Could you provide minimal code to reproduce this issue?

**Comment by ABausG** [comment]
```dart
Column(
        children: [
          StyledText.selectable(
            text: '''Selectable Styled text
            with <b>bold text in new line</b>''',
            tags: {
              'b': StyledTextTag(
                style: const TextStyle(fontWeight: FontWeight.bold),
              ),
            },
          ),
          StyledText(
            text: '''Non selectableStyled text
            with <b>bold text in new line</b>''',
            tags: {
              'b': StyledTextTag(
                style: const TextStyle(fontWeight: FontWeight.bold),
              ),
            },
          ),
        ],
      )
```

This produces:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/7288963/201868080-9f8ad309-68bf-4894-821b-8da84da49fcd.png">

**Comment by andyduke** [comment]
@ABausG `StyledText.selectable` has `newLineAsBreaks` set to **false**, unlike regular `StyledText`. Set `newLineAsBreaks` to **true** and the widgets will behave the same:
```dart
Column(
  children: [
    StyledText.selectable(
      newLineAsBreaks: true, // <---- !!!
      text: '''Selectable Styled text
      with <b>bold text in new line</b>''',
      tags: {
        'b': StyledTextTag(
          style: const TextStyle(fontWeight: FontWeight.bold),
        ),
      },
    ),
    StyledText(
      text: '''Non selectableStyled text
      with <b>bold text in new line</b>''',
      tags: {
        'b': StyledTextTag(
          style: const TextStyle(fontWeight: FontWeight.bold),
        ),
      },
    ),
  ],
)
```
