### ISSUE TITLE
const-ness of StyledTextTag

### ISSUE THREAD

**Issue by navaronbracke** [andyduke/styled_text_package#67]
## Proposal

Make the `StyledTextTagBase` and `StyledTextTag` classes have a `const` constructor.

This way we can create a const map for the tags in a `StyledText` widget.

While looking into it, I also noticed that the package sources are not formatted correctly.

**Comment by andyduke** [comment]
@navaronbracke Your suggestion has been implemented in version [9.0.0](https://pub.dev/packages/styled_text/versions/9.0.0-beta-2), thank you.
