### ISSUE TITLE
DefaultTextHeightBehavior Issue

### ISSUE THREAD

**Issue by hrithikM31** [andyduke/styled_text_package#69]
Getting the issue: 
DefaultTextHeightBehavior.of() was called with a context that does not contain a DefaultTextHeightBehavior widget.

`StyledText( text: widget.reqData.listing_name,overflow: TextOverflow.fade,  style: themeData.textTheme.headline4!.copyWith(color: Colors.black))`

**Comment by gisborne** [comment]
Same.

**Comment by andyduke** [comment]
Please provide minimal code to reproduce this problem and show the output of `flutter doctor -v`.

**Comment by gisborne** [comment]
Latest version fixes it. Please close. Sorry for the trouble.

**Comment by hrithikM31** [comment]
Yes its fixed. 
Thanks
