### ISSUE TITLE
MultiLine Support

### ISSUE THREAD

**Issue by Dri27** [andyduke/styled_text_package#7]
Hey! This Widget is awesome <3

I am formatting a loooong text, with lots of new lines... and I am aware that I have to use the breaking tags for new lines, but I was wondering if you could add an option like 'multiLine: true' or something like that, so that we don't have to deal with new lines on multiline strings.

It's just a suggestion for this widget, I don't even know if that's possible, but I hope so! Thank you for your work, it's very useful ^^

**Comment by andyduke** [comment]
Yes, that might be helpful. I will try to do this soon.

**Comment by andyduke** [comment]
@Dri27 Implemented as an isNewLineAsBreaks parameter.
