### ISSUE TITLE
Incompatible with flutter 3.22

### ISSUE THREAD

**Issue by artemsorochan** [andyduke/styled_text_package#77]
Hi, styled_text 8.1.0 is incompatible with flutter 3.22, is there any plan to update this great library? 

Thanks in advance!

**Comment by andyduke** [comment]
@artemsorochan What specific incompatibilities did you find?

**Comment by artemsorochan** [comment]
@andyduke  Sorry, I had this error "Error: Member not found: 'MediaQuery.boldTextOverride'.", and I just overridden this line locally to run the build. But now I see that after clearing the cache, the error is gone(probably dependency was not updated to the latest one).

I deeply apologize for the confusion, it should be closed.
