### ISSUE TITLE
Cannot const-ify existing `StyledTextTagBase` subclass

### ISSUE THREAD

**Issue by fingerart** [andyduke/styled_text_package#79]
<img width="775" alt="image" src="https://github.com/andyduke/styled_text_package/assets/6304197/29107df3-7863-4fd7-a22a-3f863c865bc0">

**Comment by andyduke** [comment]
You have a typo in the keyword "const".

**Comment by fingerart** [comment]
It is indeed spelled wrong, but I cannot add const to it, which makes it impossible to use enumeration to define it.
