### ISSUE TITLE
Does it support emoji ?

### ISSUE THREAD

**Issue by Brinfotech1407** [andyduke/styled_text_package#8]
I have used it like whatsapp formatting text , so if i want to display emoji in text view how can i do that ?

**Comment by andyduke** [comment]
> 
> 
> I have used it like whatsapp formatting text , so if i want to display emoji in text view how can i do that ?

Yes, you can insert them just like in a normal Text widget:
```dart
StyledText(
  text: '😃',
  styles: {},
),
```
