### ISSUE TITLE
Text.rich textScaleFactor scales twice as much

### ISSUE THREAD

**Issue by nt4f04uNd** [andyduke/styled_text_package#83]
`textScaleFactor` property comes from `MediaQuery`, when users change system font scaling in their OS.

 When using a `Text.rich` with `WidgetSpan` with `StyledText` as a child, the `textScaleFactor` scales the text twice as much, unless we explicitly specify `textScaleFactor = 1.0` on either of them

textScaleFactor=1.0

![image](https://github.com/user-attachments/assets/bc468db8-2e66-4868-b0e6-70af83ff3671)

textScaleFactor=1.3

![image](https://github.com/user-attachments/assets/7b486d79-ceb8-4f6d-a0fb-10deb793db73)

Code sample

```dart
                const Text.rich(
                  WidgetSpan(
                    child: StyledText(
                      textScaleFactor: 1.0,
                      text: 'Test: some <b>bold</b> text.',
                      tags: {
                        'b': StyledTextTag(
                          style: TextStyle(fontWeight: FontWeight.bold),
                        ),
                      },
                    ),
                  ),
                ),

                const Text.rich(
                  WidgetSpan(
                    child: StyledText(
                      text: 'Test: some <b>bold</b> text. (double scaling!)',
                      tags: {
                        'b': StyledTextTag(
                          style: TextStyle(fontWeight: FontWeight.bold),
                        ),
                      },
                    ),
                  ),
                ),
```

**Comment by andyduke** [comment]
Does this issue occur in version 8.1.0 or 9.0.0-beta-4?

**Comment by andyduke** [comment]
This is a problem on the Flutter side. It appears with nested RichText (StyledText uses RichText inside), see [#126962](https://github.com/flutter/flutter/issues/126962).

I can advise not to use StyledText inside WidgetSpan, but to lay out everything using StyledText.
